name: 'Jared Hellings, PsyD'
favicon: null
layout_spectrum: 0.01556
typography_spectrum: 0.86254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080b02'
    - '#426918'
    - '#cfd8e9'
    - '#77787a'
    - '#7ba132'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
